### ISSUE TITLE
Problem with method Flybuy.Core.Orders.fetchOrderByRedemptionCode on iOS

### ISSUE THREAD

**Issue by mjosipovic** [BILDIT-Platform/react-native-bildit-flybuy#12] opened 2021-07-01 14:27 UTC
For some orders the Flybuy.Core.Orders.fetchOrderByRedemptionCode on iOS returns the following error:
[Error: We're having trouble finding this order. Contact the store for additional details about your order.]

For the same redemptionCode method is working correctly on Android.

Here is example order which I used to reproduce this error:
{
  "customerLicensePlate": "",
  "siteDescription": "Belk Athens, GA at Georgia Square Mall near West Atlanta Hwy",
  "siteInstructions": "For Contactless Curbside Pickup, look for the yellow Store Pickup flags nearest our entrance on the Front side facing Zaxby's. Drive into one of our designated parking spaces. Let us know you’re here, and we’ll be right out. For In Store Pickup, park anywhere outside our entrance on the Front side facing Zaxby's. Look for our yellow Store Pickup flags. Come inside to the Free Store Pickup Counter near the Ladies' Department where we'll have your order waiting!",
  "siteLongitude": "-83.467764",
  "customerCarColor": "",
  "siteName": "Athens, GA",
  "siteFullAddress": "Georgia Square Mall, 3700-175 Atlanta Hwy, Athens, GA 30606",
  "redeemedAt": "2021-06-30T17:42:31.815Z",
  "redemptionCode": "9NRNEEYMW7",
  "pickupType": "curbside",
  "siteID": 17851,
  "pickupWindow": [
    "null",
    "null"
  ],
  "siteLatitude": "33.943315",
  "customerState": "en_route",
  "customerCarType": "",
  "partnerIdentifier": "7014",
  "state": "ready",
  "customerName": "MJ",
  "siteCoverPhotoURL": null,
  "customerComment": null,
  "sitePhone": "+17063530060",
  "etaAt": "2021-07-01T15:18:51.797Z",
  "id": 50803066
}

**Comment by zeabdelkhalek** [comment] 2021-07-14 21:46
The issue is probably with the native iOS SDK since the function works correctly on the Android side, we are trying to work on it with the flybuy team.

**Comment by zeabdelkhalek** [comment] 2021-07-19 15:11
Fixed in the latest version of the package, please make sure to use 0.1.5.

**Closed by zeabdelkhalek** 2021-07-19 15:11 UTC
